
services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2407
      POSTGRES_DB: atv-test
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  atv-service:
    build: ./src
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./src/.env
    ports:
      - "8080:8080"

volumes:
  postgres_data: