apiVersion: skaffold/v4beta2
kind: Config
profiles:
  - name: atv-cloud-run
    manifests:
      rawYaml:
        - resources/cloudrun.yaml
    build:
      local:
        push: true 
      platforms: ["linux/amd64"]
      artifacts:
        - image: gcr.io/services-experiments/atv-back
          context: src/
          docker:
            dockerfile: Dockerfile
          sync: {} 
    deploy:
      cloudrun:
        projectid: services-experiments
        region: us-central1