name: 'Deploy release for this production service'

on:
  push:
    branches:
      - "main"
jobs:
  pipeline:
    name: Skaffold Docker build
    runs-on: ubuntu-22.04
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - id: 'auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GOOGLE_CREDENTIALS }}'
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v2'
        with:
          cluster_name: 'accesibilidad'
          location: 'us-central1-a'
      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: 'latest'
      - name: Download secret from GCP Secret Manager
        run: |
          gcloud secrets versions access latest --secret=cert-atv-lab > src/.env

      - name: Build Docker images
        uses: hiberbee/github-action-skaffold@1.27.0
        with:
          command: run -p atv-cloud-run
          tag: ${{ github.ref_name }}

        
